### ISSUE TITLE
Support for UITableView Section indexes

### ISSUE THREAD

**Issue by ericlewis** [splinesoft/SSDataSources#41]
It appears that when trying to add section indexes (the alphabet on the right side of contacts for instance) that it is ignored.. anyone else with some experience on the matter?

**Comment by jhersh** [comment]
@ericlewis UITableView section index titles are controlled via the `UITableViewDataSource` delegate methods `
-sectionIndexTitlesForTableView:` and `-tableView:sectionForSectionIndexTitle:atIndex:`. 

Only `SSCoreDataSource` provides a default implementation for those methods. If you'd like to customize those section indexes or specify your own, you should subclass the data source you are using and override those delegate methods.

**Comment by ericlewis** [comment]
So a subclass is the only way to handle it appropriately? I can't just add the delegates to my table view controller and it work? Which I've tried to do in a few ways so far btw. Thx for the help. You need a beer fund :)

—

**Comment by jhersh** [comment]
If you are using SSDataSources, then your `UITableView`'s data source will be a subclass of `SSBaseDataSource`. You cannot add section indexes to your table by adding delegate methods to your controller because your controller is not your table's data source.

It might be neat to add some block handler properties to SSDataSources so you could specify some section indexes without having to subclass, but until then, subclassing is the way to go.
