### ISSUE TITLE
Insert at index causing indexpath with 0 for row and section!

### ISSUE THREAD

**Issue by MohamedElzohirey** [splinesoft/SSDataSources#60]
When I use insert at index this cause the inserted objects to have the same indexpath!

for example if I insert at index 0...all objects I inserted in this way will have the same indexpath (row=0,section=0)

**Comment by segiddins** [comment]
@MohamedElzohirey could you please be more specific about what unexpected behavior you're seeing? Thanks!

**Comment by MohamedElzohirey** [comment]
for example
when I insert many object at index 0
[self.myDataSource insertItem:obj1 atIndex:0]
[self.myDataSource insertItem:obj2 atIndex:0]
....
When I check again for IndexPath in cellConfigureBlock all inserted objects have the same indexpath

It should behave like NSMUtableArray when insert and index

**Comment by jhersh** [comment]
@MohamedElzohirey you inserted an item at index 0, so `SSArrayDataSource` called your `cellCreationBlock` and `cellConfigureBlock` for that item with index path (0,0). Inserting another item at index 0 will call your blocks with the new item and, again, index path (0,0).

This is correct and working properly. I gather it's not what you are after, though. Might I suggest any of these workarounds:

- Configure your cells in `cellConfigureBlock` using the item passed to the block, not the index path
- Insert your cells en masse, rather than one at a time and always at index 0

**Comment by MohamedElzohirey** [comment]
@jhersh  I got it...thanks man.
